FROM ubuntu:22.04

RUN apt update
RUN apt upgrade -y

RUN apt install -y python3 python3-pip curl

ADD flask /flask

WORKDIR /flask
RUN pip3 install -r requirements.txt 
ENV FLASK_APPLICATION=app
ENTRYPOINT ["/usr/local/bin/flask", "run", "--host=0.0.0.0"]
