version: "3.1"
services:
  adminer:
    image: adminer:latest
    restart: always
    container_name: pictureframedb-adminer
    ports:
      - 8082:8080
    depends_on:
      - slideshowdb
  slideshowdb:
    image: mysql:latest
    restart: always
    container_name: pictureframedb
    user: 1000:1000
    volumes:
      - /mnt/src/dragdropupload/db/data:/var/lib/mysql
      - /mnt/src/dragdropupload/db/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
    healthcheck:
      test: ["CMD", "curl", "-f", "http://slideshowdb:3306"]
      interval: 30s
      timeout: 30s
      retries: 5
  slideshow:
    image: jeffspiinthesky/slideshow:0.0.1
    restart: always
    container_name: slideshow
    depends_on:
      - slideshowdb
    volumes: 
      - /mnt/src/dragdropupload/uploads:/flask/static/images
    ports:
      - 80:5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://slideshow:5000"]
      interval: 30s
      timeout: 30s
      retries: 5
  slideshowclient:
    image: jeffspiinthesky/slideshow-client:0.0.1
    restart: always
    container_name: slideshowclient
    depends_on:
      - slideshow
    privileged: true
    volumes:
      - /mnt/src/dragdropupload/uploads:/images
      - /dev/fb0:/dev/fb0
      - /dev/tty2:/dev/tty2
